#!/usr/bin/env ruby
# frozen_string_literal: true
################
### Silkedit ###
################

require 'rbcli'

require File.join(File.dirname(__FILE__), '..', 'lib', 'silkedit')
Dir[File.join(File.dirname(__FILE__), '..', 'lib', 'config', '*.rb')].each { |file| require file }
Dir[File.join(File.dirname(__FILE__), '..', 'lib', 'commands', '*.rb')].each { |file| require file }

Rbcli.go!